app = "enversonvideocall"
kill_signal = "SIGINT"
kill_timeout = 10
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "PRODUCTION"
  PORT = "62947"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 62947
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
